### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by guipsamora** [ajcr/100-pandas-puzzles#1]
Hi Alex,

As a quest to better learn pandas I created a [series of exercises](https://github.com/guipsamora/pandas_exercises/) in a different form than yours. 
I would like to know if you might to be interested to contribute in any way to my repo or if I can use the your exercises.

Thanks

**Comment by ajcr** [comment]
Hi Guilherme, thanks for getting in touch. I really like the format of your exercises and the use of notebooks! I think the focus on individual topics will be of great value to people exploring pandas.

I'd be very happy to see if there's anything I can contribute to your series of exercises. In the meantime, please feel free to use/adapt any of the questions in my repo in whatever way you like. 

Alex

**Comment by guipsamora** [comment]
Hi Alex,

Thank you for your message! I'm glad you liked the exercises. :)

I like the format of yours too because it resembles more to the whole process and uses everything available. After completing all topics, my plan is to create all topics in one exercise/dataset analysis and to rank the exercises to difficult level.

If have any idea or would like to contribute creating something, I would be glad to pull your request!

Best,
Gui
