### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by jabl** [ajcr/100-pandas-puzzles#10]
It would be nice if these exercises would have a license, so one knows under which conditions one can make use of them.

I don't have any particular license in mind myself, and of course that's not my call to make, tough in the name of reducing license proliferation I would suggest to use the same license as pandas itself uses: https://github.com/pandas-dev/pandas/blob/master/LICENSE .

**Comment by ajcr** [comment]
Thank you very much for raising this issue.

I've added an MIT license to the exercises. I'm not much of an expert when it comes to licenses, but I've used the MIT license for for some of my other projects, it's what [numpy-100 exercises](https://github.com/rougier/numpy-100/blob/master/LICENSE.txt) uses, and it seems to be in very much the same spirit as the BSD 3-Clause license used by [pandas](https://github.com/pandas-dev/pandas/blob/master/LICENSE) itself.
