### ISSUE TITLE
Q22 : Use dataframe.drop_duplicates()

### ISSUE THREAD

**Issue by Incyuna2z** [ajcr/100-pandas-puzzles#11]
The built-in [drop_duplicates](http://pandas.pydata.org/pandas-docs/version/0.17/generated/pandas.DataFrame.drop_duplicates.html) makes more easier to accomplish :)

**Comment by ajcr** [comment]
Good point! That works well in this case, so I will add it as an alternative answer.

However, `drop_duplicates()` wouldn't work properly for columns such as `[1, 2, 2, 1, 1]` - you'd get `[1, 2, 1]` using the `shift()` method, but just `[1, 2]` with `drop_duplicates()`.

**Comment by ajcr** [comment]
Added! Thanks for raising the issue :-)
