### ISSUE TITLE
I'm rather new, but I think your solution for #22 does not work.

### ISSUE THREAD

**Issue by bromero26** [ajcr/100-pandas-puzzles#15]
`df[.loc[df['A'].shift() != df['A']]]` throws an SyntaxError. 
Instead, `df[df['A'].shift() != df['A']]` works.

**Comment by ajcr** [comment]
Hi @bromero26 , thanks for raising an issue.

I've just checked and it looks like the solution given in the notebook is actually `df.loc[df['A'].shift() != df['A']]` - the code you've written on your first line looks like it may have the first `[` and the `.loc` accidentally swapped around (which is a SyntaxError as you say).

You're absolutely correct that `df[df['A'].shift() != df['A']]` would be a good solution though.

**Comment by bromero26** [comment]
You're right. Thanks for putting these exercises together and I look forward to the next 40.
Cheers
