### ISSUE TITLE
The second solution to Q29 does not work propery.

### ISSUE THREAD

**Issue by Arten013** [ajcr/100-pandas-puzzles#17]
The solution below (Q29-2) output wrong answer when I input dataframe whose value starts with zero.

```Python
x = (df['X'] != 0).cumsum()
y = x != x.shift()
df['Y'] = y.groupby((y != y.shift()).cumsum()).cumsum()
```

In this code, Series `y` has to have `True` where its value is not zero and `False` otherwise.
However, the first value of `y` become `True` in any case.

e.g. 
```Python
df1 = pd.DataFrame({'X': [0, 2, 0, 3]})
df2 = pd.DataFrame({'X': [1, 2, 0, 3]})

x = (df1['X'] != 0).cumsum()
y = x != x.shift()
print(y[0])

x = (df2['X'] != 0).cumsum()
y = x != x.shift()
print(y[0])
```
outputs
```
True
True
```

This bug can be fixed by replacing first two lines into `y = df['X'] != 0`

Here's the code to compare the results between the solution 1 , solution 2 and modified solution2.

```Python
import pandas as pd
import numpy as np
df = pd.DataFrame({'X': [0, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

def solution1(df):
    izero = np.r_[-1, (df['X'] == 0).nonzero()[0]] # indices of zeros
    idx = np.arange(len(df))
    return pd.Series(idx - izero[np.searchsorted(izero - 1, idx) - 1])

def solution2(df):
    x = (df['X'] != 0).cumsum()
    y = x != x.shift()
    return y.groupby((y != y.shift()).cumsum()).cumsum()

def solution2_modified(df):
    y = df['X'] != 0
    return y.groupby((y != y.shift()).cumsum()).cumsum()

check_df = pd.concat([df, solution1(df), solution2(df), solution2_modified(df)], axis=1)
check_df.columns = ['input_df', 'solution1', 'solution2', 'solution2_modified']
display(check_df)

```
|input_df|solution1|solution2|solution2_modified|
|-------:|--------:|--------:|-----------------:|
|       0|        0|        1|                 0|
|       2|        1|        2|                 1|
|       0|        0|        0|                 0|
|       3|        1|        1|                 1|
|       4|        2|        2|                 2|
|       2|        3|        3|                 3|
|       5|        4|        4|                 4|
|       0|        0|        0|                 0|
|       3|        1|        1|                 1|
|       4|        2|        2|                 2|

I executed these code with Python 3.6.7 & pandas 0.24.0.

**Comment by ajcr** [comment]
Apologies for not seeing this issue sooner, @Arten013. I've merged the fix that you suggested which has been implemented by @pleydier. Thanks for raising the ticket!
