### ISSUE TITLE
Sorting not needed in solution to question 27.

### ISSUE THREAD

**Issue by ibah** [ajcr/100-pandas-puzzles#2]
> 27. A DataFrame has a column of groups 'grps' and and column of numbers 'vals'. For each group, find the sum of the three greatest values.

The solution starts with sorting the 'vals' column - this is not needed. The `nlargest` method selects the three greatest values irrespective of the order of element.

Suggestion: delete the sorting, the solution is provided by just by the second line of code.

**Comment by ajcr** [comment]
You're absolutely correct - thanks for pointing this out!

I've edited the solution to the puzzle accordingly.
